# Generated by Django 3.0.2 on 2020-01-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0003_auto_20200128_1700'),
        ('surveys', '0002_auto_20200126_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveysectionlink',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Section', unique=True, verbose_name='section'),
        ),
        migrations.CreateModel(
            name='SurveyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantLevelAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Power'), (2, 'Flexibility'), (3, 'Adventure'), (4, 'Vision'), (5, 'Empathy'), (6, 'Trust'), (7, 'Rest'), (8, 'Authenticity'), (9, 'Research')], verbose_name='level')),
                ('survey_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyInstance', verbose_name='Survey Instance')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='survey_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyInstance', verbose_name='Survey Instance'),
        ),
    ]
