# Generated by Django 3.0.2 on 2020-01-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(),
        ),
    ]
