# Generated by Django 3.0.2 on 2020-01-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20200128_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantlevelanswer',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='importantlevelanswer',
            unique_together={('survey_instance', 'number'), ('survey_instance', 'level')},
        ),
    ]
