# Generated by Django 3.0.2 on 2020-01-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200126_1026'),
        ('surveys', '0005_surveysectionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysectionlink',
            name='section_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_uuid', to='organisations.Section', to_field='uuid'),
        ),
    ]
