# Generated by Django 3.0.2 on 2020-01-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200129_1604'),
        ('surveys', '0006_auto_20200129_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysectionlink',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.Section', verbose_name='section'),
        ),
    ]
