# Generated by Django 3.0.2 on 2020-01-17 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation', verbose_name='organisation')),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_section', to='organisations.Section', verbose_name='parent_section')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AlterModelOptions(
            name='organisationuserlink',
            options={'verbose_name': 'User-organisation-link', 'verbose_name_plural': 'User-organisation-links'},
        ),
        migrations.AlterField(
            model_name='organisationuserlink',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='organisations.Organisation', verbose_name='organisation'),
        ),
        migrations.CreateModel(
            name='SectionUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Section', verbose_name='section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'Section-user-link',
                'verbose_name_plural': 'Section-user-links',
            },
        ),
    ]
