# Generated by Django 3.0.2 on 2020-01-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0002_organisationuserlink_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationuserlink',
            options={'verbose_name': 'user-organisation-link', 'verbose_name_plural': 'user-organisation-links'},
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organisationuserlink',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gebruiker', to='organisations.Organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='organisationuserlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organisation'),
        ),
    ]
