# Generated by Django 3.0.2 on 2020-01-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200124_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
