# Generated by Django 3.0.2 on 2020-01-26 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_section_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent_section_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbase_uuid', to='organisations.Section', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='sectionadministrator',
            name='section_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nbase_uuid', to='organisations.Section', to_field='uuid'),
        ),
        migrations.AddField(
            model_name='sectionuserlink',
            name='section_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bbase_uuid', to='organisations.Section', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='section',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a41beebd-f641-4a0e-b91f-9da6c3c8e0ff'), unique=True),
        ),
    ]
